"""Auto-generated expected schema for football-data.co.uk E0.csv."""
from __future__ import annotations

COLUMNS: list[str] = ['Div',
 'Date',
 'Time',
 'HomeTeam',
 'AwayTeam',
 'FTHG',
 'FTAG',
 'FTR',
 'HTHG',
 'HTAG',
 'HTR',
 'Referee',
 'HS',
 'AS',
 'HST',
 'AST',
 'HF',
 'AF',
 'HC',
 'AC',
 'HY',
 'AY',
 'HR',
 'AR',
 'B365H',
 'B365D',
 'B365A',
 'BFDH',
 'BFDD',
 'BFDA',
 'BMGMH',
 'BMGMD',
 'BMGMA',
 'BVH',
 'BVD',
 'BVA',
 'BWH',
 'BWD',
 'BWA',
 'CLH',
 'CLD',
 'CLA',
 'LBH',
 'LBD',
 'LBA',
 'PSH',
 'PSD',
 'PSA',
 'MaxH',
 'MaxD',
 'MaxA',
 'AvgH',
 'AvgD',
 'AvgA',
 'BFEH',
 'BFED',
 'BFEA',
 'B365>2.5',
 'B365<2.5',
 'P>2.5',
 'P<2.5',
 'Max>2.5',
 'Max<2.5',
 'Avg>2.5',
 'Avg<2.5',
 'BFE>2.5',
 'BFE<2.5',
 'AHh',
 'B365AHH',
 'B365AHA',
 'PAHH',
 'PAHA',
 'MaxAHH',
 'MaxAHA',
 'AvgAHH',
 'AvgAHA',
 'BFEAHH',
 'BFEAHA',
 'B365CH',
 'B365CD',
 'B365CA',
 'BFDCH',
 'BFDCD',
 'BFDCA',
 'BMGMCH',
 'BMGMCD',
 'BMGMCA',
 'BVCH',
 'BVCD',
 'BVCA',
 'BWCH',
 'BWCD',
 'BWCA',
 'CLCH',
 'CLCD',
 'CLCA',
 'LBCH',
 'LBCD',
 'LBCA',
 'PSCH',
 'PSCD',
 'PSCA',
 'MaxCH',
 'MaxCD',
 'MaxCA',
 'AvgCH',
 'AvgCD',
 'AvgCA',
 'BFECH',
 'BFECD',
 'BFECA',
 'B365C>2.5',
 'B365C<2.5',
 'PC>2.5',
 'PC<2.5',
 'MaxC>2.5',
 'MaxC<2.5',
 'AvgC>2.5',
 'AvgC<2.5',
 'BFEC>2.5',
 'BFEC<2.5',
 'AHCh',
 'B365CAHH',
 'B365CAHA',
 'PCAHH',
 'PCAHA',
 'MaxCAHH',
 'MaxCAHA',
 'AvgCAHH',
 'AvgCAHA',
 'BFECAHH',
 'BFECAHA']

COLUMN_INFO: dict[str, dict[str, str | None]] = {'Div': {'description': 'League Division', 'group': 'Key to results data'},
 'Date': {'description': 'Match Date (dd/mm/yy)', 'group': 'Key to results data'},
 'Time': {'description': 'Time of match kick off', 'group': 'Key to results data'},
 'HomeTeam': {'description': 'Home Team', 'group': 'Key to results data'},
 'AwayTeam': {'description': 'Away Team', 'group': 'Key to results data'},
 'FTHG': {'description': 'Full Time Home Team Goals', 'group': 'Key to results data'},
 'FTAG': {'description': 'Full Time Away Team Goals', 'group': 'Key to results data'},
 'FTR': {'description': 'Full Time Result (H=Home Win, D=Draw, A=Away Win)',
         'group': 'Key to results data'},
 'HTHG': {'description': 'Half Time Home Team Goals', 'group': 'Key to results data'},
 'HTAG': {'description': 'Half Time Away Team Goals', 'group': 'Key to results data'},
 'HTR': {'description': 'Half Time Result (H=Home Win, D=Draw, A=Away Win)',
         'group': 'Key to results data'},
 'Referee': {'description': 'Match Referee', 'group': 'Match Statistics'},
 'HS': {'description': 'Home Team Shots', 'group': 'Match Statistics'},
 'AS': {'description': 'Away Team Shots', 'group': 'Match Statistics'},
 'HST': {'description': 'Home Team Shots on Target', 'group': 'Match Statistics'},
 'AST': {'description': 'Away Team Shots on Target', 'group': 'Match Statistics'},
 'HF': {'description': 'Home Team Fouls Committed', 'group': 'Match Statistics'},
 'AF': {'description': 'Away Team Fouls Committed', 'group': 'Match Statistics'},
 'HC': {'description': 'Home Team Corners', 'group': 'Match Statistics'},
 'AC': {'description': 'Away Team Corners', 'group': 'Match Statistics'},
 'HY': {'description': 'Home Team Yellow Cards', 'group': 'Match Statistics'},
 'AY': {'description': 'Away Team Yellow Cards', 'group': 'Match Statistics'},
 'HR': {'description': 'Home Team Red Cards', 'group': 'Match Statistics'},
 'AR': {'description': 'Away Team Red Cards', 'group': 'Match Statistics'},
 'B365H': {'description': 'Bet365 home win odds', 'group': 'Match Statistics'},
 'B365D': {'description': 'Bet365 draw odds', 'group': 'Match Statistics'},
 'B365A': {'description': 'Bet365 away win odds', 'group': 'Match Statistics'},
 'BFDH': {'description': 'Betfred home win odds', 'group': 'Match Statistics'},
 'BFDD': {'description': 'Betfred draw odds', 'group': 'Match Statistics'},
 'BFDA': {'description': 'Betfred away win odds', 'group': 'Match Statistics'},
 'BMGMH': {'description': 'BetMGM home win odds', 'group': 'Match Statistics'},
 'BMGMD': {'description': 'BetMGM draw odds', 'group': 'Match Statistics'},
 'BMGMA': {'description': 'BetMGM away win odds', 'group': 'Match Statistics'},
 'BVH': {'description': 'Betvictor home win odds', 'group': 'Match Statistics'},
 'BVD': {'description': 'Betvictor draw odds', 'group': 'Match Statistics'},
 'BVA': {'description': 'Betvictor away win odds', 'group': 'Match Statistics'},
 'BWH': {'description': 'Bet&Win home win odds', 'group': 'Match Statistics'},
 'BWD': {'description': 'Bet&Win draw odds', 'group': 'Match Statistics'},
 'BWA': {'description': 'Bet&Win away win odds', 'group': 'Match Statistics'},
 'CLH': {'description': 'Coral home win odds', 'group': 'Match Statistics'},
 'CLD': {'description': 'Coral draw odds', 'group': 'Match Statistics'},
 'CLA': {'description': 'Coral away win odds', 'group': 'Match Statistics'},
 'LBH': {'description': 'Ladbrokes home win odds', 'group': 'Match Statistics'},
 'LBD': {'description': 'Ladbrokes draw odds', 'group': 'Match Statistics'},
 'LBA': {'description': 'Ladbrokes away win odds', 'group': 'Match Statistics'},
 'PSH': {'description': 'Pinnacle home win odds', 'group': 'Match Statistics'},
 'PSD': {'description': 'Pinnacle draw odds', 'group': 'Match Statistics'},
 'PSA': {'description': 'Pinnacle away win odds', 'group': 'Match Statistics'},
 'MaxH': {'description': 'Market maximum home win odds', 'group': 'Match Statistics'},
 'MaxD': {'description': 'Market maximum draw win odds', 'group': 'Match Statistics'},
 'MaxA': {'description': 'Market maximum away win odds', 'group': 'Match Statistics'},
 'AvgH': {'description': 'Market average home win odds', 'group': 'Match Statistics'},
 'AvgD': {'description': 'Market average draw win odds', 'group': 'Match Statistics'},
 'AvgA': {'description': 'Market average away win odds', 'group': 'Match Statistics'},
 'BFEH': {'description': 'Betfair Exchange home win odds', 'group': 'Match Statistics'},
 'BFED': {'description': 'Betfair Exchange draw odds', 'group': 'Match Statistics'},
 'BFEA': {'description': 'Betfair Exchange away win odds', 'group': 'Match Statistics'},
 'B365>2.5': {'description': 'Bet365 over 2.5 goals', 'group': 'Key to total goals betting odds'},
 'B365<2.5': {'description': 'Bet365 under 2.5 goals', 'group': 'Key to total goals betting odds'},
 'P>2.5': {'description': 'Pinnacle over 2.5 goals', 'group': 'Key to total goals betting odds'},
 'P<2.5': {'description': 'Pinnacle under 2.5 goals', 'group': 'Key to total goals betting odds'},
 'Max>2.5': {'description': 'Market maximum over 2.5 goals',
             'group': 'Key to total goals betting odds'},
 'Max<2.5': {'description': 'Market maximum under 2.5 goals',
             'group': 'Key to total goals betting odds'},
 'Avg>2.5': {'description': 'Market average over 2.5 goals',
             'group': 'Key to total goals betting odds'},
 'Avg<2.5': {'description': 'Market average under 2.5 goals',
             'group': 'Key to total goals betting odds'},
 'BFE>2.5': {'description': 'Unknown description (not in notes.txt)', 'group': None},
 'BFE<2.5': {'description': 'Unknown description (not in notes.txt)', 'group': None},
 'AHh': {'description': 'Market size of handicap (home team) (since 2019/2020)',
         'group': 'Key to Asian handicap betting odds'},
 'B365AHH': {'description': 'Bet365 Asian handicap home team odds',
             'group': 'Key to Asian handicap betting odds'},
 'B365AHA': {'description': 'Bet365 Asian handicap away team odds',
             'group': 'Key to Asian handicap betting odds'},
 'PAHH': {'description': 'Pinnacle Asian handicap home team odds',
          'group': 'Key to Asian handicap betting odds'},
 'PAHA': {'description': 'Pinnacle Asian handicap away team odds',
          'group': 'Key to Asian handicap betting odds'},
 'MaxAHH': {'description': 'Market maximum Asian handicap home team odds',
            'group': 'Key to Asian handicap betting odds'},
 'MaxAHA': {'description': 'Market maximum Asian handicap away team odds',
            'group': 'Key to Asian handicap betting odds'},
 'AvgAHH': {'description': 'Market average Asian handicap home team odds',
            'group': 'Key to Asian handicap betting odds'},
 'AvgAHA': {'description': 'Market average Asian handicap away team odds',
            'group': 'Key to Asian handicap betting odds'},
 'BFEAHH': {'description': 'Unknown description (not in notes.txt)', 'group': None},
 'BFEAHA': {'description': 'Unknown description (not in notes.txt)', 'group': None},
 'B365CH': {'description': 'Closing Bet365 home win odds', 'group': 'Match Statistics'},
 'B365CD': {'description': 'Closing Bet365 draw odds', 'group': 'Match Statistics'},
 'B365CA': {'description': 'Closing Bet365 away win odds', 'group': 'Match Statistics'},
 'BFDCH': {'description': 'Closing Betfred home win odds', 'group': 'Match Statistics'},
 'BFDCD': {'description': 'Closing Betfred draw odds', 'group': 'Match Statistics'},
 'BFDCA': {'description': 'Closing Betfred away win odds', 'group': 'Match Statistics'},
 'BMGMCH': {'description': 'Closing BetMGM home win odds', 'group': 'Match Statistics'},
 'BMGMCD': {'description': 'Closing BetMGM draw odds', 'group': 'Match Statistics'},
 'BMGMCA': {'description': 'Closing BetMGM away win odds', 'group': 'Match Statistics'},
 'BVCH': {'description': 'Closing Betvictor home win odds', 'group': 'Match Statistics'},
 'BVCD': {'description': 'Closing Betvictor draw odds', 'group': 'Match Statistics'},
 'BVCA': {'description': 'Closing Betvictor away win odds', 'group': 'Match Statistics'},
 'BWCH': {'description': 'Closing Bet&Win home win odds', 'group': 'Match Statistics'},
 'BWCD': {'description': 'Closing Bet&Win draw odds', 'group': 'Match Statistics'},
 'BWCA': {'description': 'Closing Bet&Win away win odds', 'group': 'Match Statistics'},
 'CLCH': {'description': 'Unknown description (not in notes.txt)', 'group': None},
 'CLCD': {'description': 'Unknown description (not in notes.txt)', 'group': None},
 'CLCA': {'description': 'Unknown description (not in notes.txt)', 'group': None},
 'LBCH': {'description': 'Closing Ladbrokes home win odds', 'group': 'Match Statistics'},
 'LBCD': {'description': 'Closing Ladbrokes draw odds', 'group': 'Match Statistics'},
 'LBCA': {'description': 'Closing Ladbrokes away win odds', 'group': 'Match Statistics'},
 'PSCH': {'description': 'Closing Pinnacle home win odds', 'group': 'Match Statistics'},
 'PSCD': {'description': 'Closing Pinnacle draw odds', 'group': 'Match Statistics'},
 'PSCA': {'description': 'Closing Pinnacle away win odds', 'group': 'Match Statistics'},
 'MaxCH': {'description': 'Closing Market maximum home win odds', 'group': 'Match Statistics'},
 'MaxCD': {'description': 'Closing Market maximum draw win odds', 'group': 'Match Statistics'},
 'MaxCA': {'description': 'Closing Market maximum away win odds', 'group': 'Match Statistics'},
 'AvgCH': {'description': 'Closing Market average home win odds', 'group': 'Match Statistics'},
 'AvgCD': {'description': 'Closing Market average draw win odds', 'group': 'Match Statistics'},
 'AvgCA': {'description': 'Closing Market average away win odds', 'group': 'Match Statistics'},
 'BFECH': {'description': 'Closing Betfair Exchange home win odds', 'group': 'Match Statistics'},
 'BFECD': {'description': 'Closing Betfair Exchange draw odds', 'group': 'Match Statistics'},
 'BFECA': {'description': 'Closing Betfair Exchange away win odds', 'group': 'Match Statistics'},
 'B365C>2.5': {'description': 'Closing Bet365 over 2.5 goals',
               'group': 'Key to total goals betting odds'},
 'B365C<2.5': {'description': 'Closing Bet365 under 2.5 goals',
               'group': 'Key to total goals betting odds'},
 'PC>2.5': {'description': 'Closing Pinnacle over 2.5 goals',
            'group': 'Key to total goals betting odds'},
 'PC<2.5': {'description': 'Closing Pinnacle under 2.5 goals',
            'group': 'Key to total goals betting odds'},
 'MaxC>2.5': {'description': 'Closing Market maximum over 2.5 goals',
              'group': 'Key to total goals betting odds'},
 'MaxC<2.5': {'description': 'Closing Market maximum under 2.5 goals',
              'group': 'Key to total goals betting odds'},
 'AvgC>2.5': {'description': 'Closing Market average over 2.5 goals',
              'group': 'Key to total goals betting odds'},
 'AvgC<2.5': {'description': 'Closing Market average under 2.5 goals',
              'group': 'Key to total goals betting odds'},
 'BFEC>2.5': {'description': 'Unknown description (not in notes.txt)', 'group': None},
 'BFEC<2.5': {'description': 'Unknown description (not in notes.txt)', 'group': None},
 'AHCh': {'description': 'Closing Market size of handicap (home team) (since 2019/2020)',
          'group': 'Key to Asian handicap betting odds'},
 'B365CAHH': {'description': 'Closing Bet365 Asian handicap home team odds',
              'group': 'Key to Asian handicap betting odds'},
 'B365CAHA': {'description': 'Closing Bet365 Asian handicap away team odds',
              'group': 'Key to Asian handicap betting odds'},
 'PCAHH': {'description': 'Closing Pinnacle Asian handicap home team odds',
           'group': 'Key to Asian handicap betting odds'},
 'PCAHA': {'description': 'Closing Pinnacle Asian handicap away team odds',
           'group': 'Key to Asian handicap betting odds'},
 'MaxCAHH': {'description': 'Closing Market maximum Asian handicap home team odds',
             'group': 'Key to Asian handicap betting odds'},
 'MaxCAHA': {'description': 'Closing Market maximum Asian handicap away team odds',
             'group': 'Key to Asian handicap betting odds'},
 'AvgCAHH': {'description': 'Closing Market average Asian handicap home team odds',
             'group': 'Key to Asian handicap betting odds'},
 'AvgCAHA': {'description': 'Closing Market average Asian handicap away team odds',
             'group': 'Key to Asian handicap betting odds'},
 'BFECAHH': {'description': 'Unknown description (not in notes.txt)', 'group': None},
 'BFECAHA': {'description': 'Unknown description (not in notes.txt)', 'group': None}}

EXPECTED_SCHEMA: dict[str, object] = {'columns': COLUMNS, 'column_info': COLUMN_INFO}


def describe(code: str) -> str:
    info = COLUMN_INFO.get(code)
    if info is None:
        return f"{code}: Unknown description"
    group = info.get('group')
    desc = info.get('description', '')
    if group:
        return f"{code} ({group}): {desc}"
    return f"{code}: {desc}"
